application: scrabblish
version: 1
runtime: go
api_version: 2

handlers:
- url: /twl
  static_files: scrabblish/twl.txt
  upload: scrabblish/twl.txt
- url: /
  static_files: scrabblish.html
  upload: scrabblish.html
- url: /solve
  script: _go_app
