application: interesaint
version: 1
runtime: go
api_version: 3

handlers:
- url: /
  static_files: interesaint.html
  upload: interesaint.html
  login: required
- url: /add
  script: _go_app
  login: required
- url: /tasks/.*
  script: _go_app
  login: admin

