application: interesaint
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: interesaint.html
  upload: interesaint.html
  login: required
- url: /images
  static_dir: images
- url: /script/.*
  script: interesaint.app
  login: required
- url: /tasks/.*
  script: interesaint.app
  login: admin

libraries:
- name: numpy
  version: latest

