application: meepesh
version: 1
runtime: go
api_version: go1

handlers:
# Main page.
- url: /
  static_files: index.html
  upload: index.html
  login: required
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
# Magic CSS.
- url: /style.less
  static_files: style.less
  upload: style.less
# Most of the required JavaScript to load.
- url: /(.*\.js)
  static_files: \1
  upload: .*\.js
# JSColor.
- url: /jscolor
  static_dir: jscolor
# API interface to persisted worlds.
- url: /backend/.*
  script: _go_app
  login: required
