application: pebblescores
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /configuration.html
  static_files: configuration.html
  upload: configuration.html
- url: /nonce
  script: pebblescores.app
- url: /submit
  script: pebblescores.app
- url: /list
  script: pebblescores.app
