application: pebblescores
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /(.*\.(html|js|css))
  static_file: \1
  upload: (.*\.(html|js|css))
- url: /nonce
  script: pebblescores.app
- url: /submit
  script: pebblescores.app
- url: /list
  script: pebblescores.app
