application: keestand-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always
- url: /old_sjcl.js
  static_files: old_sjcl.js
  upload: old_sjcl.js
  secure: always
- url: /sjcl.js
  static_files: sjcl.js
  upload: sjcl.js
  secure: always
- url: /ucsv-1.2.0.min.js
  static_files: ucsv-1.2.0.min.js
  upload: ucsv-1.2.0.min.js
  secure: always
- url: /keestand.js
  static_files: keestand.js
  upload: keestand.js
  secure: always
- url: /css
  static_dir: css
  secure: always
- url: /
  static_files: keestand.html
  upload: keestand.html
  secure: always
- url: /cache.manifest
  mime_type: text/cache-manifest
  static_files: cache.manifest
  upload: cache.manifest
  secure: always
- url: /script/.*
  script: keestand.app
  secure: always
