application: keestand
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /sjcl.js
  static_files: sjcl.js
  upload: sjcl.js
- url: /
  static_files: keestand.html
  upload: keestand.html
  secure: always
- url: /script/.*
  script: keestand.py
  secure: always
