application: keestand
version: 1
runtime: python
api_version: 1

handlers:
- url: /crypto
  static_dir: crypto
- url: /
  static_files: login.html
  upload: login.html
- url: /edit
  static_files: edit.html
  upload: edit.html
- url: /script/.*
  script: keestand.py
