application: keestand
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: login.html
  upload: login.html
- url: /script/login
  script: keestand.py
- url: /edit
  static_files: edit.html
  upload: edit.html
- url: /script/edit
  script: keestand.py
