application: keestand
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: login.html
  upload: login.html
- url: /sha1.js
  static_files: sha1.js
  upload: sha1.js
- url: /(view|edit)
  script: keestand.py
