application: keestand
version: 1
runtime: python
api_version: 1

handlers:
- url: /sjcl.js
  static_files: sjcl.js
  upload: sjcl.js
- url: /
  static_files: login.html
  upload: login.html
  secure: always
- url: /edit
  static_files: edit.html
  upload: edit.html
  secure: always
- url: /script/.*
  script: keestand.py
  secure: always
