application: keestand
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /css
  static_dir: css
  secure: always
- url: /sjcl.js
  static_files: sjcl.js
  upload: sjcl.js
  secure: always
- url: /
  static_files: keestand.html
  upload: keestand.html
  secure: always
- url: /script/.*
  script: keestand.py
  secure: always
