application: blockfort3d
version: 1
runtime: go
api_version: go1

handlers:
# Main page.
- url: /
  static_files: index.html
  upload: index.html
  login: required
- url: /blockfort.gif
  static_files: blockfort.gif
  upload: blockfort.gif
- url: /crosshair.png
  static_files: crosshair.png
  upload: crosshair.png
# Magic CSS.
- url: /style.less
  static_files: style.less
  upload: style.less
# Most of the required JavaScript to load.
- url: /(.*\.js)
  static_files: \1
  upload: .*\.js
# JSColor.
- url: /jscolor
  static_dir: jscolor
# Load either named or IDed world.
- url: /load
  script: _go_app
  login: required
# Save named  world, returning ID.
- url: /save
  script: _go_app
  login: required
